const express = require("express")
const port = 3000;
const app = express()
var bodyParser = require('body-parser')
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
const router = express.Router()
const AuthRouter = require("./src/router/auth.router")
const AuthController = require("./src/controller/auth.controller")
const AuthMiddleware = require("./src/auth/authmiddleware")
const ClassRouter = require("./src/router/class.router")
const StudentRouter = require("./src/router/student.router")
const SubjectRouter = require("./src/router/subject.rourter")
const GradeRouter = require("./src/router/grade.router")
const AssignmentRouter = require("./src/router/assignment.router")
const NotificationRouter = require("./src/router/notificaiton.router")
router.post("/register", AuthController.register)
router.post("/login", AuthController.login)
app.use("/public/api", router)
app.use("/public/api", AuthRouter)
// app.use(AuthMiddleware.is_Auth)
app.use("/public/api", ClassRouter)
app.use("/public/api", StudentRouter)
app.use("/public/api", SubjectRouter)
app.use("/public/api", GradeRouter)
app.use("/public/api", AssignmentRouter)
app.use("/public/api", NotificationRouter)

app.listen(port, function () {
    console.log("server start on :", port)
})

