const express = require('express')
const router = express.Router()
const GradeController = require("../controller/grade.controller")
router.post("/add-grade", GradeController.addGrade)
router.get("/get-all-grade", GradeController.getAllGrade)
router.get("/get-grade-summary/:id", GradeController.getAllByClassSummary)
router.get("/get-all-subject-by-student/:id", GradeController.getAllSubjectByStudent)
router.post("/get-grade-by-class-and-student", GradeController.getAllSubjectByClassStudent)
router.post("/get-grade-student-academicyear", GradeController.getGradeByStudentAcademicYear)
router.post("/get-grade-subject-class", GradeController.getAllGradeSubjectClass)
// router.get("/get-grade-by-class/:class", GradeController.ge)
router.put("/update-grade", GradeController.updateGrade)
router.delete("/delete-grade/:id", GradeController.deleteGrade)
module.exports = router
